### ISSUE TITLE
roc_smi example has a bug.

### ISSUE THREAD

**Issue by reza-amd** [ROCm/rocm_smi_lib#98]
Looking at the example [here](https://github.com/RadeonOpenCompute/rocm_smi_lib/blob/66e101a0ffb49df3c34f14e8669856381ce8d23d/rocm_smi/example/rocm_smi_example.cc#L428), device ID is returned in ```val_ui16```, but instead ```val_ui64 ``` is being used as the ID. The example probably need an statement such as ```val_ui64 = val_ui16``` immediately after ```rsmi_dev_id_get``` call.

**Comment by ppanchad-amd** [comment]
@reza-amd Please check if this still occurs with the latest ROCm 6.2. If not, please close the ticket. Thanks!

**Comment by harkgill-amd** [comment]
Hi @reza-amd, this issue has since been resolved and the latest implemenatation of `rsmi_num_monitor_devices` can be found [here ](https://github.com/ROCm/rocm_smi_lib/blob/amd-staging/rocm_smi/example/rocm_smi_example.cc#L787). 

In the snippet below, we can see that now val_ui16 is being returned and also used as the device ID.

```
  rsmi_num_monitor_devices(&num_monitor_devs);
  for (uint32_t i = 0; i < num_monitor_devs; ++i) {
    std::cout << "\t**Device #: " << std::dec << i << "\n";
    ret = rsmi_dev_id_get(i, &val_ui16);
    CHK_RSMI_RET_I(ret)
    std::cout << "\t**Device ID: 0x" << std::hex << val_ui16 << "\n";
```
